version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
    volumes:
      - ${PWD}/fs/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d